package io.std.agendaelectronica.igu;

public class Principal extends javax.swing.JFrame {

  private String[] dnis = new String[10];
  private String[] nombres = new String[10];
  private String[] apellidos = new String[10];
  private String[] direcciones = new String[10];
  private String[] telefonos = new String[10];
  private String[] fechasNacimientos = new String[10];

  /**
   * Creates new form Principal
   */
  public Principal() {
    initComponents();
  }

  private void cargarCampos(int index) {
    this.campoDni.setText(this.dnis[index]);
    this.campoApellido.setText(this.apellidos[index]);
    this.campoNombre.setText(this.nombres[index]);
    this.campoDireccion.setText(this.direcciones[index]);
    this.campoTelefono.setText(this.telefonos[index]);
    this.campoFechaNacimiento.setText(this.fechasNacimientos[index]);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelGeneral = new javax.swing.JPanel();
    panelTitulo = new javax.swing.JPanel();
    titulo = new javax.swing.JLabel();
    panelFormulario = new javax.swing.JPanel();
    panelCampoDni = new javax.swing.JPanel();
    etiquetaDni = new javax.swing.JLabel();
    campoDni = new javax.swing.JTextField();
    panelCampoDireccion = new javax.swing.JPanel();
    etiquetaDireccion = new javax.swing.JLabel();
    campoDireccion = new javax.swing.JTextField();
    panelCampoNombre = new javax.swing.JPanel();
    etiquetaNombre = new javax.swing.JLabel();
    campoNombre = new javax.swing.JTextField();
    panelCampoTelefono = new javax.swing.JPanel();
    etiquetaTelefono = new javax.swing.JLabel();
    campoTelefono = new javax.swing.JTextField();
    panelCampoFechaNacimiento = new javax.swing.JPanel();
    etiquetaFechaNacimiento = new javax.swing.JLabel();
    campoFechaNacimiento = new javax.swing.JTextField();
    panelCampoApellido = new javax.swing.JPanel();
    etiquetaApellido = new javax.swing.JLabel();
    campoApellido = new javax.swing.JTextField();
    panelBotones = new javax.swing.JPanel();
    botonRetroceder = new javax.swing.JButton();
    botonGrabar = new javax.swing.JButton();
    botonAdelantar = new javax.swing.JButton();
    indice = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    titulo.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
    titulo.setText("Agenda Electrónica");

    javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
    panelTitulo.setLayout(panelTituloLayout);
    panelTituloLayout.setHorizontalGroup(
      panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelTituloLayout.createSequentialGroup()
        .addGap(105, 105, 105)
        .addComponent(titulo)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    panelTituloLayout.setVerticalGroup(
      panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelTituloLayout.createSequentialGroup()
        .addComponent(titulo)
        .addGap(0, 12, Short.MAX_VALUE))
    );

    etiquetaDni.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
    etiquetaDni.setText("DNI:");

    campoDni.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

    javax.swing.GroupLayout panelCampoDniLayout = new javax.swing.GroupLayout(panelCampoDni);
    panelCampoDni.setLayout(panelCampoDniLayout);
    panelCampoDniLayout.setHorizontalGroup(
      panelCampoDniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelCampoDniLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelCampoDniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(etiquetaDni)
          .addComponent(campoDni, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    panelCampoDniLayout.setVerticalGroup(
      panelCampoDniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelCampoDniLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(etiquetaDni)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(campoDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    etiquetaDireccion.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
    etiquetaDireccion.setText("Dirección:");

    campoDireccion.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

    javax.swing.GroupLayout panelCampoDireccionLayout = new javax.swing.GroupLayout(panelCampoDireccion);
    panelCampoDireccion.setLayout(panelCampoDireccionLayout);
    panelCampoDireccionLayout.setHorizontalGroup(
      panelCampoDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelCampoDireccionLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelCampoDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(etiquetaDireccion)
          .addComponent(campoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    panelCampoDireccionLayout.setVerticalGroup(
      panelCampoDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelCampoDireccionLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(etiquetaDireccion)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(campoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    etiquetaNombre.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
    etiquetaNombre.setText("Nombre:");

    campoNombre.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

    javax.swing.GroupLayout panelCampoNombreLayout = new javax.swing.GroupLayout(panelCampoNombre);
    panelCampoNombre.setLayout(panelCampoNombreLayout);
    panelCampoNombreLayout.setHorizontalGroup(
      panelCampoNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelCampoNombreLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelCampoNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(etiquetaNombre)
          .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    panelCampoNombreLayout.setVerticalGroup(
      panelCampoNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelCampoNombreLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(etiquetaNombre)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    etiquetaTelefono.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
    etiquetaTelefono.setText("Teléfono:");

    campoTelefono.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

    javax.swing.GroupLayout panelCampoTelefonoLayout = new javax.swing.GroupLayout(panelCampoTelefono);
    panelCampoTelefono.setLayout(panelCampoTelefonoLayout);
    panelCampoTelefonoLayout.setHorizontalGroup(
      panelCampoTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelCampoTelefonoLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelCampoTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(etiquetaTelefono)
          .addComponent(campoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    panelCampoTelefonoLayout.setVerticalGroup(
      panelCampoTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelCampoTelefonoLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(etiquetaTelefono)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(campoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    etiquetaFechaNacimiento.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
    etiquetaFechaNacimiento.setText("Fecha de nacimiento:");

    campoFechaNacimiento.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

    javax.swing.GroupLayout panelCampoFechaNacimientoLayout = new javax.swing.GroupLayout(panelCampoFechaNacimiento);
    panelCampoFechaNacimiento.setLayout(panelCampoFechaNacimientoLayout);
    panelCampoFechaNacimientoLayout.setHorizontalGroup(
      panelCampoFechaNacimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelCampoFechaNacimientoLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelCampoFechaNacimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(etiquetaFechaNacimiento)
          .addComponent(campoFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    panelCampoFechaNacimientoLayout.setVerticalGroup(
      panelCampoFechaNacimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelCampoFechaNacimientoLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(etiquetaFechaNacimiento)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(campoFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    etiquetaApellido.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
    etiquetaApellido.setText("Apellido:");

    campoApellido.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

    javax.swing.GroupLayout panelCampoApellidoLayout = new javax.swing.GroupLayout(panelCampoApellido);
    panelCampoApellido.setLayout(panelCampoApellidoLayout);
    panelCampoApellidoLayout.setHorizontalGroup(
      panelCampoApellidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelCampoApellidoLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelCampoApellidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(etiquetaApellido)
          .addComponent(campoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    panelCampoApellidoLayout.setVerticalGroup(
      panelCampoApellidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelCampoApellidoLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(etiquetaApellido)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(campoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    botonRetroceder.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
    botonRetroceder.setText("<<");
    botonRetroceder.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonRetrocederActionPerformed(evt);
      }
    });

    botonGrabar.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
    botonGrabar.setText("Grabar");
    botonGrabar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonGrabarActionPerformed(evt);
      }
    });

    botonAdelantar.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
    botonAdelantar.setText(">>");
    botonAdelantar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonAdelantarActionPerformed(evt);
      }
    });

    indice.setEditable(false);
    indice.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
    indice.setText("1");

    javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
    panelBotones.setLayout(panelBotonesLayout);
    panelBotonesLayout.setHorizontalGroup(
      panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelBotonesLayout.createSequentialGroup()
        .addGap(121, 121, 121)
        .addComponent(botonRetroceder, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(botonGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(panelBotonesLayout.createSequentialGroup()
            .addGap(43, 43, 43)
            .addComponent(indice, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(botonAdelantar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    panelBotonesLayout.setVerticalGroup(
      panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelBotonesLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(botonRetroceder)
          .addComponent(botonGrabar)
          .addComponent(botonAdelantar))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(indice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout panelFormularioLayout = new javax.swing.GroupLayout(panelFormulario);
    panelFormulario.setLayout(panelFormularioLayout);
    panelFormularioLayout.setHorizontalGroup(
      panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelFormularioLayout.createSequentialGroup()
        .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addGroup(panelFormularioLayout.createSequentialGroup()
            .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(panelCampoDni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addGroup(panelFormularioLayout.createSequentialGroup()
                .addComponent(panelCampoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(panelCampoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(panelCampoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addGroup(panelFormularioLayout.createSequentialGroup()
            .addComponent(panelCampoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(panelCampoFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(panelFormularioLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    panelFormularioLayout.setVerticalGroup(
      panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelFormularioLayout.createSequentialGroup()
        .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(panelCampoDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(panelCampoDni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(panelCampoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(panelCampoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(panelCampoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(panelCampoFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout panelGeneralLayout = new javax.swing.GroupLayout(panelGeneral);
    panelGeneral.setLayout(panelGeneralLayout);
    panelGeneralLayout.setHorizontalGroup(
      panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelGeneralLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(panelFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    panelGeneralLayout.setVerticalGroup(
      panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelGeneralLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(panelFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panelGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panelGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void botonRetrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRetrocederActionPerformed
    int numero = 0;
    String valor = this.indice.getText();
    numero = Integer.parseInt(valor);
    if (numero > 1) {
      numero = numero - 1;
    }
    this.cargarCampos(numero - 1);
    valor = String.valueOf(numero);
    this.indice.setText(valor);
  }//GEN-LAST:event_botonRetrocederActionPerformed

  private void botonAdelantarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAdelantarActionPerformed
    int numero = 0;
    String valor = this.indice.getText();
    numero = Integer.parseInt(valor);
    if (numero < 10) {
      numero = numero + 1;
    }
    this.cargarCampos(numero - 1);
    valor = String.valueOf(numero);
    this.indice.setText(valor);
  }//GEN-LAST:event_botonAdelantarActionPerformed

  private void botonGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGrabarActionPerformed
    int numero = 0;
    String valor = this.indice.getText();
    numero = Integer.parseInt(valor) - 1;
    this.dnis[numero] = this.campoDni.getText();
    this.nombres[numero] = this.campoNombre.getText();
    this.apellidos[numero] = this.campoApellido.getText();
    this.telefonos[numero] = this.campoTelefono.getText();
    this.direcciones[numero] = this.campoDireccion.getText();
    this.fechasNacimientos[numero] = this.campoFechaNacimiento.getText();
  }//GEN-LAST:event_botonGrabarActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton botonAdelantar;
  private javax.swing.JButton botonGrabar;
  private javax.swing.JButton botonRetroceder;
  private javax.swing.JTextField campoApellido;
  private javax.swing.JTextField campoDireccion;
  private javax.swing.JTextField campoDni;
  private javax.swing.JTextField campoFechaNacimiento;
  private javax.swing.JTextField campoNombre;
  private javax.swing.JTextField campoTelefono;
  private javax.swing.JLabel etiquetaApellido;
  private javax.swing.JLabel etiquetaDireccion;
  private javax.swing.JLabel etiquetaDni;
  private javax.swing.JLabel etiquetaFechaNacimiento;
  private javax.swing.JLabel etiquetaNombre;
  private javax.swing.JLabel etiquetaTelefono;
  private javax.swing.JTextField indice;
  private javax.swing.JPanel panelBotones;
  private javax.swing.JPanel panelCampoApellido;
  private javax.swing.JPanel panelCampoDireccion;
  private javax.swing.JPanel panelCampoDni;
  private javax.swing.JPanel panelCampoFechaNacimiento;
  private javax.swing.JPanel panelCampoNombre;
  private javax.swing.JPanel panelCampoTelefono;
  private javax.swing.JPanel panelFormulario;
  private javax.swing.JPanel panelGeneral;
  private javax.swing.JPanel panelTitulo;
  private javax.swing.JLabel titulo;
  // End of variables declaration//GEN-END:variables
}
